export const RECEIVERS = [
  {
    num: 1,
    name: 'Tecsun PL-310ET / PL-380',
    desc: 'Цифровой DSP-приёмник эталонного качества. Идеальная чувствительность на СВ, отображение уровня сигнала, термометр. Любимец выживальщиков.',
    price: '~ 6 500 – 8 500 ₽',
    links: [{ label: 'Ozon', url: 'https://www.ozon.ru/category/radiopriemniki-15545/?text=Tecsun+PL-310ET', color: 'bg-blue-700' }],
  },
  {
    num: 2,
    name: 'Degen DE1103',
    desc: 'Легенда радиоприёма. Мощнейший всеволновый приёмник с отличной ферритовой антенной. Берёт очень слабые сигналы за десятки километров.',
    price: '~ 10 000 – 14 000 ₽',
    links: [{ label: 'Wildberries', url: 'https://www.wildberries.ru/catalog/0/search.aspx?search=Degen+DE1103', color: 'bg-purple-700' }],
  },
  {
    num: 3,
    name: 'Retekess V115',
    desc: 'Бюджетный цифровой хит. Ловит AM/FM/SW, имеет mp3-плеер и диктофон (умеет записывать эфир на флешку). Заряжается как телефон.',
    price: '~ 1 800 – 2 500 ₽',
    links: [{ label: 'Ozon', url: 'https://www.ozon.ru/category/radiopriemniki-15545/?text=Retekess+V115', color: 'bg-blue-700' }],
  },
  {
    num: 4,
    name: 'Ritmix RPR-050',
    desc: 'Классический аналоговый дизайн «под ретро». Отличная громкость, ловит СВ (AM) и КВ. Питание от сети или батареек D.',
    price: '~ 1 900 – 2 600 ₽',
    links: [{ label: 'DNS', url: 'https://www.dns-shop.ru/search/?q=Ritmix+RPR-050', color: 'bg-orange-700' }],
  },
  {
    num: 5,
    name: 'Harper HDR-10',
    desc: 'Недорогие и надёжные «походные» приёмники с механической шкалой настройки. Есть FM и AM. Дёшево и сердито.',
    price: '~ 1 200 – 1 800 ₽',
    links: [{ label: 'Ozon', url: 'https://www.ozon.ru/category/radiopriemniki-15545/?text=Harper+HDR-10', color: 'bg-blue-700' }],
  },
  {
    num: 6,
    name: 'Panasonic RF-2400D',
    desc: 'Японское качество тюнера. Аналоговая шкала, очень цепкий приёмник на AM-волнах без лишних шумов.',
    price: '~ 4 200 – 5 500 ₽',
    links: [{ label: 'Wildberries', url: 'https://www.wildberries.ru/catalog/0/search.aspx?search=Panasonic+RF-2400', color: 'bg-purple-700' }],
  },
  {
    num: 7,
    name: 'XHDATA D-808',
    desc: 'Аналог Tecsun, мощный цифровой сканер. Питается от аккумулятора 18650, отлично ловит СВ и КВ, есть Авиа диапазон.',
    price: '~ 8 500 – 10 000 ₽',
    links: [{ label: 'Ozon', url: 'https://www.ozon.ru/category/radiopriemniki-15545/?text=XHDATA+D-808', color: 'bg-blue-700' }],
  },
  {
    num: 8,
    name: 'Max MR-321',
    desc: 'Доступные приёмники в DNS/Ситилинке. Простая аналоговая крутилка, есть AM-диапазон. Хорошо для неприхотливых слушателей.',
    price: '~ 800 – 1 500 ₽',
    links: [{ label: 'DNS', url: 'https://www.dns-shop.ru/search/?q=Max+MR-321', color: 'bg-orange-700' }],
  },
  {
    num: 9,
    name: 'KIPO KB-308AC',
    desc: 'Один из самых массовых и дешёвых. Отлично ловит СВ (AM) за счёт длинной ферритовой антенны.',
    price: '~ 700 – 1 200 ₽',
    links: [{ label: 'Wildberries', url: 'https://www.wildberries.ru/catalog/0/search.aspx?search=KIPO+KB-308', color: 'bg-purple-700' }],
  },
  {
    num: 10,
    name: 'Любая автомагнитола',
    desc: 'Практически все автомобильные магнитолы (Pioneer, JVC, Kenwood, штатные ГУ) имеют кнопку AM/MW. Автомобильная антенна отлично ловит СВ.',
    price: 'Бесплатно (в авто)',
    links: [],
  },
]
